### ISSUE TITLE
partials do not work (iojs 1.8.1, windows 7.1)

### ISSUE THREAD

**Issue by Dzenly** [dominicbarnes/koa-handlebars#13]
The following log says, that partials are found and compiled, but at render log says that partials not found:
There is nothing about registration in readme.

Wed, 06 May 2015 10:12:38 GMT koa-handlebars creating koa-handlebars instance with options { cache: false,
  root: 'd:/MyLife/Programming/TimeIsAllRepo/TimeIsAll/dev/src/timeisall',
  viewsDir: 'views',
  layoutsDir: 'views',
  partialsDir: 'views/partials',
  defaultLayout: 'layout' }
Wed, 06 May 2015 10:12:38 GMT koa-handlebars using d:/MyLife/Programming/TimeIsAllRepo/TimeIsAll/dev/src/timeisall as the root
Wed, 06 May 2015 10:12:42 GMT koa-handlebars rendering index template
Wed, 06 May 2015 10:12:42 GMT koa-handlebars reading file views\layout.hbs
Wed, 06 May 2015 10:12:42 GMT koa-handlebars compiling template views\layout.hbs
Wed, 06 May 2015 10:12:42 GMT koa-handlebars reading file views\index.hbs
Wed, 06 May 2015 10:12:42 GMT koa-handlebars compiling template views\index.hbs
Wed, 06 May 2015 10:12:42 GMT koa-handlebars searching for partials in d:\MyLife\Programming\TimeIsAllRepo\TimeIsAll\dev\src\timeisall\views\partials
Wed, 06 May 2015 10:12:42 GMT koa-handlebars 4 partials found
Wed, 06 May 2015 10:12:42 GMT koa-handlebars reading file views\partials\auth_widget.hbs
Wed, 06 May 2015 10:12:42 GMT koa-handlebars reading file views\partials\home_skeleton.hbs
Wed, 06 May 2015 10:12:42 GMT koa-handlebars compiling template views\partials\auth_widget.hbs
Wed, 06 May 2015 10:12:42 GMT koa-handlebars compiling template views\partials\home_skeleton.hbs
Wed, 06 May 2015 10:12:42 GMT koa-handlebars rendering with layout layout
Wed, 06 May 2015 10:12:42 GMT koa-handlebars unable to render view index Error: The partial home_skeleton could not be found
    at Object.invokePartial (d:\MyLife\Programming\TimeIsAllRepo\TimeIsAll\dev\src\timeisall\node_modules\koa-handlebars\node_modules\handlebars\dist\cjs\handlebars\runtime.js:216:11)
    at Object.invokePartialWrapper [as invokePartial] (d:\MyLife\Programming\TimeIsAllRepo\TimeIsAll\dev\src\timeisall\node_modules\koa-handlebars\node_modules\handlebars\dist\cjs\handlebars\runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (d:\MyLife\Programming\TimeIsAllRepo\TimeIsAll\dev\src\timeisall\node_modules\koa-handlebars\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:221:23), <anonymous>:4:23)
    at Object.ret (d:\MyLife\Programming\TimeIsAllRepo\TimeIsAll\dev\src\timeisall\node_modules\koa-handlebars\node_modules\handlebars\dist\cjs\handlebars\runtime.js:159:30)
    at Object.ret [as fn] (d:\MyLife\Programming\TimeIsAllRepo\TimeIsAll\dev\src\timeisall\node_modules\koa-handlebars\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:488:21)
    at Object.Renderer.compileTemplate.meta.render (d:\MyLife\Programming\TimeIsAllRepo\TimeIsAll\dev\src\timeisall\node_modules\koa-handlebars\lib\renderer.js:85:17)
    at Renderer.render (d:\MyLife\Programming\TimeIsAllRepo\TimeIsAll\dev\src\timeisall\node_modules\koa-handlebars\lib\renderer.js:313:38)
    at GeneratorFunctionPrototype.next (native)
    at onFulfilled (d:\MyLife\Programming\TimeIsAllRepo\TimeIsAll\dev\src\timeisall\node_modules\koa\node_modules\co\index.js:64:19)

Probably similar problem (unanswered yet).
http://stackoverflow.com/questions/29309198/koa-handlebars-unable-to-render-view-the-partial-could-not-be-found

**Comment by dominicbarnes** [comment]
That's really weird, I don't see this problem on Mac/Linux, and I don't own any Windows machines. Would you be able to help trace down this problem?

**Comment by dominicbarnes** [comment]
Oh wait... I think I might know what's going on.

The default behavior is to camelCase the partial filename. (especially when nested in dirs because "/" can break templates) (see [docs](https://github.com/dominicbarnes/koa-handlebars#partialidfile))

To verify if this is the case, try using `homeSkeleton` **instead of** `home_skeleton`?

If that turns out to be the issue, and you don't want that behavior, you can use a custom `partialId(file)` function like:

```js
partialId: function (file) {
  return file; // maybe you can replace "/" with something else
}
```

**Comment by Dzenly** [comment]
Thank you for fast and helpful answer!
Filenames without "-, _" and separate directories for layouts, partials, views solved the problem.

P.S.

I am moving from express/hbs to koa now, and choosing the template engine.

koa-handlebars has this limitation for filenames and does not support {{{body}}} (only {{{@body}}}), but uses handlebars 3.0.0. 

koa-hbs has not such limitation on file names, but uses old (2.0.0) handlebars :)

**Comment by dominicbarnes** [comment]
Why is `@body` a disadvantage compared to `body`? (it's a [feature of handlebars](http://handlebarsjs.com/reference.html#data))

Also, I don't know if I'd consider this behavior a "limitation" for partial filenames, it's intended to make the names cleaner in the templates themselves. However, this is not the first time this has caused confusion, so I may find a way to make this more predictable.

**Comment by Dzenly** [comment]
Handlebars.js examples use {{body}}. And http://handlebarsjs.com/reference.html#data page does not contain "@body" entries, so I consider this as a tiny incompatibility, because I should correct template from my old project. It is very subjective of course. :)
